package com.amiiboroom.ordercollector.util.enums;

public enum SiteType {

    NAVER, SOFRANOMALL, GAMEWOORI, DAEWONSHOP, BANDAIMALL, AUCTION, GMARKET, COUPANG, TMON, YES24, COMICSART, GUNDAMBOOM, KYOUMASHOP, H2MALL,
    AMAZON, PLAYASIA, AMIAMI, LIMITEDRUN, MERCARI, ALIEXPRESS

}
