spring:
  config:
    activate:
      on-profile: [application.yml에 선언할 프로파일값 ex. local, test, real]
  datasource:
    url: jdbc:postgresql://[DB주소]/[DB명]
    username: DB 아이디
    password: DB 비밀번호
jasypt:
  encryptor:
    password: 암호화에 사용하는 키값
    salt: 암호화에 사용하는 솔트값