#common config
spring:
  profiles:
    active: local
#    active: test
#    active: real
    group:
      local: local, local_secret
      test: test, test_secret
      real: real, real_secret
  datasource:
    driver-class-name: org.postgresql.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/queries/*.xml

# Settings to use encryption in yml files
#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor
#    property:
#      prefix: Enc(
#      suffix: )

---

# local config
spring:
  config:
    activate:
      on-profile: local

server:
  port: 3030

logging:
  level:
    root: info

---

# test config
spring:
  config:
    activate:
      on-profile: test

server:
  port: 3030

logging:
  level:
    root: info

---

# real config
spring:
  config:
    activate:
      on-profile: real

server:
  port: 8080

logging:
  level:
    root: warn